--
-- Tables
-- This file declares all tables in the public schema.
--

-- Extensions
create extension if not exists "http" with schema "extensions";

-- Private schema (used by sales policies migration)
create schema if not exists "private";

create table public.companies (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone not null default now(),
    name text not null,
    sector text,
    size smallint,
    linkedin_url text,
    website text,
    phone_number text,
    address text,
    zipcode text,
    city text,
    state_abbr text,
    sales_id bigint,
    context_links json,
    country text,
    description text,
    revenue text,
    tax_identifier text,
    logo jsonb,
    escritorio_id bigint
);

create table public.contacts (
    id bigint generated by default as identity primary key,
    first_name text,
    last_name text,
    gender text,
    title text,
    background text,
    avatar jsonb,
    first_seen timestamp with time zone,
    last_seen timestamp with time zone,
    has_newsletter boolean,
    status text,
    tags bigint[],
    company_id bigint,
    sales_id bigint,
    linkedin_url text,
    email_jsonb jsonb,
    phone_jsonb jsonb,
    escritorio_id bigint,
    -- Aba 1: Informações Pessoais
    alias text,
    person_type text,
    document text,
    date_of_birth date,
    xp_code text,
    monthly_income numeric,
    website text,
    -- Aba 2: Perfil do Investidor
    segment text,
    investor_profile text,
    declared_wealth numeric,
    xp_account_type text,
    xp_international boolean,
    investment_horizon text,
    financial_goal text,
    relationship_start_date date,
    xp_code_2 text,
    mb_code text,
    avenue_code text,
    origin text,
    referred_by text,
    cross_sell_opportunities text[],
    internal_notes text,
    -- Aba 3: Endereço
    zip_code text,
    address text,
    address_number text,
    address_complement text,
    neighborhood text,
    city text,
    state text,
    country text,
    address_notes text,
    constraint contacts_document_unique unique (document)
);

create table public.contact_notes (
    id bigint generated by default as identity (sequence name public."contactNotes_id_seq") not null,
    contact_id bigint not null,
    text text,
    date timestamp with time zone default now(),
    sales_id bigint,
    status text,
    attachments jsonb[],
    escritorio_id bigint
);

create table public.pipelines (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone not null default now(),
    name text not null,
    stages jsonb not null default '[]'::jsonb,
    pipeline_statuses text[] not null default '{}',
    position smallint not null default 0,
    escritorio_id bigint
);

create table public.deals (
    id bigint generated by default as identity primary key,
    name text not null,
    company_id bigint,
    contact_ids bigint[],
    category text,
    stage text not null,
    pipeline_id bigint,
    description text,
    amount bigint,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    archived_at timestamp with time zone,
    expected_closing_date date,
    sales_id bigint,
    index smallint,
    escritorio_id bigint
);

create table public.deal_notes (
    id bigint generated by default as identity (sequence name public."dealNotes_id_seq") not null,
    deal_id bigint not null,
    type text,
    text text,
    date timestamp with time zone default now(),
    sales_id bigint,
    attachments jsonb[],
    escritorio_id bigint
);

create table public.escritorios (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone not null default now(),
    name text not null
);

create table public.sales (
    id bigint generated by default as identity primary key,
    first_name text not null default 'Pending'::text,
    last_name text not null default 'Pending'::text,
    email text not null,
    administrator boolean not null,
    user_id uuid not null,
    avatar jsonb,
    disabled boolean not null default false,
    escritorio_id bigint,
    papel text not null default 'assessor' check (papel in ('gestor', 'assessor'))
);

create unique index uq__sales__user_id on public.sales using btree (user_id);

create table public.tags (
    id bigint generated by default as identity primary key,
    name text not null,
    color text not null,
    escritorio_id bigint
);

create table public.tasks (
    id bigint generated by default as identity primary key,
    contact_id bigint not null,
    type text,
    text text,
    due_date date,
    done_date timestamp with time zone,
    sales_id bigint,
    escritorio_id bigint,
    start_time text,
    end_time text,
    end_date date,
    notes text,
    deal_id bigint,
    source text default 'manual',
    external_id text,
    external_url text,
    metadata jsonb default '{}'::jsonb
);

create table public.configuration (
    id integer not null default 1 primary key,
    config jsonb not null default '{}'::jsonb,
    constraint configuration_singleton check (id = 1)
);

create table public.favicons_excluded_domains (
    id bigint generated by default as identity primary key,
    domain text not null
);

--
-- Foreign keys
--

alter table public.companies
    add constraint companies_sales_id_fkey foreign key (sales_id) references public.sales(id);

alter table public.contacts
    add constraint contacts_company_id_fkey foreign key (company_id) references public.companies(id) on update cascade on delete cascade;

alter table public.contacts
    add constraint contacts_sales_id_fkey foreign key (sales_id) references public.sales(id);

alter table public.contact_notes
    add constraint "contactNotes_contact_id_fkey" foreign key (contact_id) references public.contacts(id) on update cascade on delete cascade;

alter table public.contact_notes
    add constraint "contactNotes_sales_id_fkey" foreign key (sales_id) references public.sales(id) on update cascade on delete cascade;

alter table public.pipelines
    add constraint pipelines_escritorio_id_fkey foreign key (escritorio_id) references public.escritorios(id);

alter table public.deals
    add constraint deals_company_id_fkey foreign key (company_id) references public.companies(id) on update cascade on delete cascade;

alter table public.deals
    add constraint deals_sales_id_fkey foreign key (sales_id) references public.sales(id);

alter table public.deals
    add constraint deals_pipeline_id_fkey foreign key (pipeline_id) references public.pipelines(id);

alter table public.deal_notes
    add constraint "dealNotes_deal_id_fkey" foreign key (deal_id) references public.deals(id) on update cascade on delete cascade;

alter table public.deal_notes
    add constraint "dealNotes_sales_id_fkey" foreign key (sales_id) references public.sales(id);

alter table public.sales
    add constraint sales_user_id_fkey foreign key (user_id) references auth.users(id);

alter table public.sales
    add constraint sales_escritorio_id_fkey foreign key (escritorio_id) references public.escritorios(id);

alter table public.tasks
    add constraint tasks_contact_id_fkey foreign key (contact_id) references public.contacts(id) on update cascade on delete cascade;

-- Legacy primary key constraint names (from before snake_case rename)
alter table only public.contact_notes
    add constraint "contactNotes_pkey" primary key (id);

alter table only public.deal_notes
    add constraint "dealNotes_pkey" primary key (id);

alter table public.companies
    add constraint companies_escritorio_id_fkey foreign key (escritorio_id) references public.escritorios(id);

alter table public.contacts
    add constraint contacts_escritorio_id_fkey foreign key (escritorio_id) references public.escritorios(id);

alter table public.contact_notes
    add constraint contact_notes_escritorio_id_fkey foreign key (escritorio_id) references public.escritorios(id);

alter table public.deals
    add constraint deals_escritorio_id_fkey foreign key (escritorio_id) references public.escritorios(id);

alter table public.deal_notes
    add constraint deal_notes_escritorio_id_fkey foreign key (escritorio_id) references public.escritorios(id);

alter table public.tags
    add constraint tags_escritorio_id_fkey foreign key (escritorio_id) references public.escritorios(id);

alter table public.tasks
    add constraint tasks_escritorio_id_fkey foreign key (escritorio_id) references public.escritorios(id);

alter table public.tasks
    add constraint tasks_deal_id_fkey foreign key (deal_id) references public.deals(id) on update cascade on delete set null;

--
-- Indexes on foreign keys
--

create index contact_notes_contact_id_idx on public.contact_notes using btree (contact_id);
create index contacts_company_id_idx on public.contacts using btree (company_id);
create index deal_notes_deal_id_idx on public.deal_notes using btree (deal_id);
create index deals_company_id_idx on public.deals using btree (company_id);
create index deals_pipeline_id_idx on public.deals using btree (pipeline_id);
create index tasks_deal_id_idx on public.tasks using btree (deal_id);
create unique index tasks_external_id_source_idx on public.tasks (external_id, source) where external_id is not null;
