-- Migration: Criar tabela escritorios e adicionar escritorio_id + papel em sales
-- Parte do roadmap de multi-tenancy para Family Office CRM

-- 1. Criar tabela de escritórios
create table public.escritorios (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone not null default now(),
    name text not null
);

-- 2. Habilitar RLS na nova tabela
alter table public.escritorios enable row level security;

-- 3. Políticas de acesso para escritorios
create policy "Enable read for authenticated users" on public.escritorios for select to authenticated using (true);
create policy "Enable insert for admins" on public.escritorios for insert to authenticated with check (public.is_admin());
create policy "Enable update for admins" on public.escritorios for update to authenticated using (public.is_admin()) with check (public.is_admin());
create policy "Enable delete for admins" on public.escritorios for delete to authenticated using (public.is_admin());

-- 4. Adicionar colunas escritorio_id e papel em sales
alter table public.sales
    add column escritorio_id bigint,
    add column papel text not null default 'assessor' check (papel in ('gestor', 'assessor'));

-- 5. FK de sales para escritorios
alter table public.sales
    add constraint sales_escritorio_id_fkey
    foreign key (escritorio_id) references public.escritorios(id);

-- 6. Atualizar handle_new_user para propagar escritorio_id e papel do metadata
CREATE OR REPLACE FUNCTION "public"."handle_new_user"() RETURNS "trigger"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO ''
    AS $$
declare
  sales_count int;
begin
  select count(id) into sales_count
  from public.sales;

  insert into public.sales (first_name, last_name, email, user_id, administrator, escritorio_id, papel)
  values (
    coalesce(new.raw_user_meta_data ->> 'first_name', new.raw_user_meta_data -> 'custom_claims' ->> 'first_name', 'Pending'),
    coalesce(new.raw_user_meta_data ->> 'last_name', new.raw_user_meta_data -> 'custom_claims' ->> 'last_name', 'Pending'),
    new.email,
    new.id,
    case when sales_count > 0 then FALSE else TRUE end,
    (new.raw_user_meta_data ->> 'escritorio_id')::bigint,
    coalesce(new.raw_user_meta_data ->> 'papel', 'assessor')
  );
  return new;
end;
$$;
